CREATE TABLE users
(
  id BIGINT NOT NULL
  AUTO_INCREMENT,
  name VARCHAR
  (255) NOT NULL,
  email VARCHAR
  (255) NOT NULL,
  password VARCHAR
  (255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY
  (id)
) ENGINE=InnoDB;